@localhost = localhost:3000 
@prodhost = soccer-api.onrender.com

// LOCALHOST

### Get All Teams
GET http://{{localhost}}/api/v1/teams

### Get Team
GET http://{{localhost}}/api/v1/teams/634a0eb33a25999a702753ba


### Create New Team
POST http://{{localhost}}/api/v1/teams HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Premier League"
}

### Update Team
PUT http://{{localhost}}/api/v1/teams/634a0eb33a25999a702753ba HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Bundesliga"
}

### Delete Team
DELETE http://{{localhost}}/api/v1/teams/635420dceb53cc797df22a4a


### Get All Players
GET http://{{localhost}}/api/v1/players


### Get Player
GET http://{{localhost}}/api/v1/players/635daeeff04bea73b26eb40c

### Create New Player
POST http://{{localhost}}/api/v1/players HTTP/1.1 
content-type: application/json

{
    "firstName": "Walter",
    "lastName": "Ribeiro",
    "birthDate": "12/11/1981",
    "team": "6349fbcfc93bf2a5d5c2de6e",
    "isHealthy": true,
    "bestFoot": "left",
    "position": "RWB"
}

### Update Player
PUT http://{{localhost}}/api/v1/players/635db6ea7e5841675e9c9024 HTTP/1.1 
content-type: application/json

{
    "firstName": "Walter",
    "lastName": "Casa Grande",
    "birthDate": "12/11/1981",
    "team": "6349fbcfc93bf2a5d5c2de6e",
    "isHealthy": true,
    "bestFoot": "left",
    "position": "RWB"
}

### Delete Player
DELETE http://{{localhost}}/api/v1/players/635db6ea7e5841675e9c9024



// PRODUCTION

### Get All Teams
GET http://{{prodhost}}/api/v1/teams

### Get Team
GET http://{{prodhost}}/api/v1/teams/634a0eb33a25999a702753ba


### Create New Team
POST http://{{prodhost}}/api/v1/teams HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Premier League"
}

### Update Team
PUT http://{{prodhost}}/api/v1/teams/6354240151eba41f05903b2e HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Bundesliga"
}

### Delete Team
DELETE http://{{prodhost}}/api/v1/teams/6354240151eba41f05903b2e
