@host = soccer-api.onrender.com

// PRODUCTION

### Get All Teams
GET http://{{host}}/api/v1/teams

### Get Team
GET http://{{host}}/api/v1/teams/634a0eb33a25999a702753ba


### Create New Team
POST http://{{host}}/api/v1/teams HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Premier League"
}

### Update Team
PUT http://{{host}}/api/v1/teams/6354240151eba41f05903b2e HTTP/1.1 
content-type: application/json

{
    "name": "Manchest United",
    "dateCreated": "12/11/1981",
    "league": "Bundesliga"
}

### Delete Team
DELETE http://{{host}}/api/v1/teams/6354240151eba41f05903b2e
